<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CoffeePos.Application\CoffeePos.Application.csproj" />
    <ProjectReference Include="..\CoffeePos.Infrastructure\CoffeePos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
