<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\api\src\CoffeePos.Application\CoffeePos.Application.csproj" />
    <ProjectReference Include="..\..\..\api\src\CoffeePos.Infrastructure\CoffeePos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
